sudo: false
language: node_js
node_js:
    - "10"
    - "12"
    - "14"
cache:
    directories:
        - node_modules
script:
    - npm run test
    - npm run coveralls
notifications:
    webhooks: https://coveralls.io/webhook